from __future__ import annotations

import json
from datetime import datetime, timezone
from uuid import UUID, uuid4

from app.models.memory import ActorContext, MemorySummaryResponse
from app.models.memory_extraction import LlmAnalysisOptions, MemoryExtractionFromChunksRequest
from app.services.llm_analysis import LlmCandidateDraft
from app.services.memory_extraction_service import MemoryExtractionService


class FakeDatabase:
    def __init__(self, rows):
        self.rows = rows
        self.audit_rows = []

    def connection(self):
        return FakeConnection(self)


class FakeConnection:
    def __init__(self, database: FakeDatabase) -> None:
        self.database = database

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback) -> None:
        return None

    def cursor(self):
        return FakeCursor(self.database)

    def commit(self) -> None:
        return None


class FakeCursor:
    def __init__(self, database: FakeDatabase) -> None:
        self.database = database
        self._rows = []

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback) -> None:
        return None

    def execute(self, query, params):
        if "FROM source_chunk" in query:
            self._rows = self.database.rows
            return
        if "INSERT INTO audit_log" in query:
            self.database.audit_rows.append(json.loads(params["after_json"]))

    def fetchall(self):
        return self._rows


class FakeMemoryService:
    def __init__(self) -> None:
        self.created = []

    def create_memory(self, payload, actor):
        self.created.append((payload, actor))
        now = datetime(2026, 6, 14, tzinfo=timezone.utc)
        return MemorySummaryResponse(
            memory_id=uuid4(),
            workspace_id=payload.workspace_id,
            created_from_doc_id=payload.created_from_doc_id,
            memory_type=payload.memory_type,
            canonical_text=payload.canonical_text,
            summary=payload.summary,
            confidence=payload.confidence,
            importance=payload.importance,
            status=payload.status,
            access_level=payload.access_level,
            current_revision_no=1,
            created_at=now,
            updated_at=now,
            evidence_count=len(payload.evidence),
        )


class FakeLlmClient:
    def __init__(self, chunk_id: UUID) -> None:
        self.chunk_id = chunk_id
        self.calls = []

    def analyze(self, *, chunks, max_candidates, options):
        self.calls.append(
            {"chunks": chunks, "max_candidates": max_candidates, "options": options}
        )
        return [
            LlmCandidateDraft(
                chunk_id=self.chunk_id,
                canonical_text="Private budget notes must stay hidden from project agents.",
                memory_type="policy",
                summary="Private budget visibility",
                confidence=0.88,
                importance=4,
            )
        ]


def test_llm_extraction_writes_candidate_with_llm_fields() -> None:
    workspace_id = uuid4()
    doc_id = uuid4()
    chunk_id = uuid4()
    database = FakeDatabase(
        [
            {
                "chunk_id": chunk_id,
                "doc_id": doc_id,
                "chunk_no": 1,
                "chunk_text": "Private budget notes must stay hidden from project agents.",
                "start_line": 3,
                "end_line": 3,
            }
        ]
    )
    memory_service = FakeMemoryService()
    llm_client = FakeLlmClient(chunk_id)
    service = MemoryExtractionService(
        database=database,
        memory_service=memory_service,
        llm_client=llm_client,
    )

    candidates = service.extract_from_chunks(
        MemoryExtractionFromChunksRequest(
            workspace_id=workspace_id,
            chunk_ids=[chunk_id],
            max_candidates=2,
            method="llm",
            llm=LlmAnalysisOptions(api_key="test-key", model="analysis-model"),
        ),
        ActorContext(actor_type="system", revision_reason="test extraction"),
    )

    assert len(candidates) == 1
    created_payload, _actor = memory_service.created[0]
    assert created_payload.status == "candidate"
    assert created_payload.memory_type == "policy"
    assert created_payload.confidence == 0.88
    assert created_payload.importance == 4
    assert created_payload.evidence[0].chunk_id == chunk_id
    assert created_payload.evidence[0].note == "Generated by LLM-backed memory extraction."
    assert llm_client.calls[0]["options"].api_key == "test-key"
    assert database.audit_rows[0]["method"] == "llm"
    assert database.audit_rows[0]["llm"]["model"] == "analysis-model"
