from __future__ import annotations

import json
import re
from dataclasses import dataclass
from uuid import UUID, uuid4

from ..core.database import Database
from ..models.memory import (
    ActorContext,
    MemoryCreateRequest,
    MemoryEvidenceInput,
    MemoryListResponse,
    MemorySummaryResponse,
    MemoryUpdateRequest,
)
from ..models.memory_extraction import MemoryExtractionFromChunksRequest
from .memory_service import MemoryService


class MemoryExtractionValidationError(Exception):
    pass


@dataclass(slots=True)
class MemoryExtractionService:
    database: Database
    memory_service: MemoryService

    def extract_from_chunks(
        self,
        payload: MemoryExtractionFromChunksRequest,
        actor: ActorContext,
    ) -> list[MemorySummaryResponse]:
        # Extraction writes candidate memories, not active facts. Human/admin review
        # promotes or rejects them through the same memory lifecycle used elsewhere.
        chunk_rows = self._fetch_chunks(payload.workspace_id, payload.chunk_ids)
        if len(chunk_rows) != len(set(payload.chunk_ids)):
            raise MemoryExtractionValidationError(
                "all chunk_ids must exist and belong to the requested workspace"
            )

        run_id = uuid4()
        # Run-level audit lets the demo answer "which chunks produced these
        # candidate memories" without introducing extra analysis-run tables.
        self._insert_run_audit(
            workspace_id=payload.workspace_id,
            actor=actor,
            action_type="memory_extraction.run.start",
            after_json={
                "run_id": str(run_id),
                "method": "rule-based",
                "requested_chunk_ids": [str(chunk_id) for chunk_id in payload.chunk_ids],
                "max_candidates": payload.max_candidates,
            },
        )

        candidates: list[MemorySummaryResponse] = []
        seen_text: set[str] = set()
        for row in chunk_rows:
            for text in _candidate_texts(str(row["chunk_text"])):
                normalized = text.lower()
                if normalized in seen_text:
                    continue
                seen_text.add(normalized)
                candidates.append(
                    self.memory_service.create_memory(
                        MemoryCreateRequest(
                            workspace_id=payload.workspace_id,
                            created_from_doc_id=row["doc_id"],
                            memory_type=_classify_memory_type(text),
                            canonical_text=text,
                            summary=_summary(text),
                            confidence=0.65,
                            importance=_importance(text),
                            status="candidate",
                            access_level="project",
                            evidence=[
                                MemoryEvidenceInput(
                                    chunk_id=row["chunk_id"],
                                    evidence_role="source",
                                    weight=1.0,
                                    note="Generated by rule-based memory extraction.",
                                )
                            ],
                        ),
                        actor,
                    )
                )
                if len(candidates) >= payload.max_candidates:
                    self._insert_run_audit(
                        workspace_id=payload.workspace_id,
                        actor=actor,
                        action_type="memory_extraction.run.complete",
                        after_json={
                            "run_id": str(run_id),
                            "candidate_count": len(candidates),
                            "candidate_memory_ids": [
                                str(candidate.memory_id) for candidate in candidates
                            ],
                        },
                    )
                    return candidates
        self._insert_run_audit(
            workspace_id=payload.workspace_id,
            actor=actor,
            action_type="memory_extraction.run.complete",
            after_json={
                "run_id": str(run_id),
                "candidate_count": len(candidates),
                "candidate_memory_ids": [str(candidate.memory_id) for candidate in candidates],
            },
        )
        return candidates

    def list_candidates(
        self,
        *,
        workspace_id: UUID | None,
        memory_type: str | None,
        keyword: str | None,
        page: int,
        page_size: int,
    ) -> MemoryListResponse:
        return self.memory_service.list_memories(
            workspace_id=workspace_id,
            memory_type=memory_type,
            status="candidate",
            access_level=None,
            keyword=keyword,
            page=page,
            page_size=page_size,
        )

    def approve_candidate(
        self,
        memory_id: UUID,
        workspace_id: UUID,
        actor: ActorContext,
    ) -> MemorySummaryResponse:
        detail = self.memory_service.update_memory(
            memory_id,
            workspace_id,
            MemoryUpdateRequest(status="active"),
            actor,
        )
        return MemorySummaryResponse(**detail.model_dump(exclude={"evidence", "revisions"}))

    def reject_candidate(
        self,
        memory_id: UUID,
        workspace_id: UUID,
        actor: ActorContext,
    ) -> MemorySummaryResponse:
        detail = self.memory_service.update_memory(
            memory_id,
            workspace_id,
            MemoryUpdateRequest(status="rejected"),
            actor,
        )
        return MemorySummaryResponse(**detail.model_dump(exclude={"evidence", "revisions"}))

    def _fetch_chunks(
        self,
        workspace_id: UUID,
        chunk_ids: list[UUID],
    ) -> list[dict[str, object]]:
        with self.database.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT sc.chunk_id, sc.doc_id, sc.chunk_text
                    FROM source_chunk sc
                    JOIN source_document sd ON sd.doc_id = sc.doc_id
                    WHERE sd.workspace_id = %(workspace_id)s
                      AND sd.status = 'active'
                      AND sc.chunk_id = ANY(%(chunk_ids)s::uuid[])
                    ORDER BY sc.chunk_no ASC
                    """,
                    {"workspace_id": workspace_id, "chunk_ids": chunk_ids},
                )
                return cur.fetchall()

    def _insert_run_audit(
        self,
        *,
        workspace_id: UUID,
        actor: ActorContext,
        action_type: str,
        after_json: dict[str, object],
    ) -> None:
        with self.database.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO audit_log (
                        workspace_id,
                        actor_type,
                        actor_id,
                        action_type,
                        target_type,
                        target_id,
                        after_json
                    )
                    VALUES (
                        %(workspace_id)s,
                        %(actor_type)s,
                        %(actor_id)s,
                        %(action_type)s,
                        'workspace',
                        %(workspace_id)s,
                        %(after_json)s::jsonb
                    )
                    """,
                    {
                        "workspace_id": workspace_id,
                        "actor_type": actor.actor_type,
                        "actor_id": actor.actor_id,
                        "action_type": action_type,
                        "after_json": json.dumps(after_json),
                    },
                )
            conn.commit()


def _candidate_texts(chunk_text: str) -> list[str]:
    normalized = " ".join(chunk_text.split())
    if not normalized:
        return []
    parts = [
        part.strip(" -")
        for part in re.split(r"(?<=[.!?。！？])\s+|\n+", normalized)
        if part.strip(" -")
    ]
    if not parts:
        parts = [normalized]
    return [part[:1000] for part in parts if len(part) >= 12]


def _classify_memory_type(text: str) -> str:
    lowered = text.lower()
    if any(term in lowered for term in ("decided", "decision", "选择", "决定")):
        return "decision"
    if any(term in lowered for term in ("must", "constraint", "required", "必须", "约束")):
        return "constraint"
    if any(term in lowered for term in ("policy", "permission", "权限", "规则")):
        return "policy"
    if any(term in lowered for term in ("risk", "blocked", "风险")):
        return "risk"
    if any(term in lowered for term in ("todo", "task", "should", "任务", "应该")):
        return "task"
    if any(term in lowered for term in ("prefer", "preference", "偏好")):
        return "preference"
    return "fact"


def _importance(text: str) -> int:
    memory_type = _classify_memory_type(text)
    if memory_type in {"decision", "constraint", "policy", "risk"}:
        return 4
    return 3


def _summary(text: str) -> str:
    compact = " ".join(text.split())
    if len(compact) <= 80:
        return compact
    return compact[:77].rstrip() + "..."
